name: Build
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run dist
